### ISSUE TITLE
DateTimePicker click on "Arrow" doesn't work

### ISSUE THREAD

**Issue by payammeyer** [gwtbootstrap3/gwtbootstrap3-extras#140] opened 2015-02-27 17:11 UTC
Clicking on the arrow icon itself has odd behavior. Clicking slightly under the arrow does what it's supposed to do, but clicking the arrow itself does different things depending on your settings, i.e. if you have autoClose="true", it closes the picker. Noticed that the icon is a `<span>` element instead of an `<i>` element. Manually changing the element in chrome debugger fixes the issue.

**Comment by mainFC** [comment] 2015-02-28 01:34
This is the same issue I have raised in #137.

**Comment by jgodi** [comment] 2015-03-06 13:42
This is a bug in the underlying library that the DateTimePicker uses: https://github.com/smalot/bootstrap-datetimepicker/issues/313. When that is fixed and a new release, then we will update it.

**Comment by payammeyer** [comment] 2015-03-06 13:49
How come the bug isn't present in their demo? Do they use a newer version of that library?

http://www.malot.fr/bootstrap-datetimepicker/demo.php

**Comment by jgodi** [comment] 2015-03-06 13:51
Their demo is using v2 of Bootstrap, they have auto detection to wrap out the templates in their JS. So we get the v3 versions of the templates, which have the spans.

**Comment by payammeyer** [comment] 2015-03-06 13:52
Ok got it, thanks.

**Comment by mdavis95** [comment] 2015-03-13 15:13
Can this be used instead:
https://github.com/eternicode/bootstrap-datepicker

Seems to support bootstrap 3 in the demo:
http://eternicode.github.io/bootstrap-datepicker/

**Comment by jgodi** [comment] 2015-03-15 15:10
Changing the base library that we wrap might be a bit of work, but I am game for switching if someone can create a PR for it.

**Comment by mdavis95** [comment] 2015-03-15 15:14
Fair enough, I will give it a try

**Comment by crevete** [comment] 2015-03-15 21:55
@mdavis95 @jgodi or this one: https://github.com/Eonasdan/bootstrap-datetimepicker
I think this one is better.
Anyway, smalot/bootstrap-datetimepicker is not "alive", it should be replaced by something else.

**Comment by mdavis95** [comment] 2015-03-15 23:55
@jgodi Do you have a preference? I can take a shot at either.

**Comment by jgodi** [comment] 2015-03-16 00:19
I like the one @crevete linked. If you are feeling over zealous you can try to fix the bugs for formatting and stuff too :)

Appreciate the help!

**Comment by mdavis95** [comment] 2015-03-18 17:32
I tried to do the Eonasdan one but I have no luck.  I created a branch for it if anyone would like to continue (https://github.com/mdavis95/gwtbootstrap3-extras/tree/eonasdan).  It is quite different.

The eternicode version I was able to get working and created a pull request for it.  It is only a date picker instead of a date time picker however.

**Comment by Unimax** [comment] 2015-06-03 17:06
why no work is done on datetimepicker from http://eonasdan.github.io/bootstrap-datetimepicker/
@mdavis95 i would like to try ur approach, what are the issue u faced for time-picker? as u seem to already done the date-picker.
a similar demo can be found on http://svenjacobs.github.io/gwtbootstrap3/ who seems to ported a older version , can start from there or from scratch.

**Comment by jgodi** [comment] 2015-06-03 17:30
We currently have a [DateTimePicker](http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#dateTimePicker) implemented. But this uses an older [version](http://www.malot.fr/bootstrap-datetimepicker/) of a Bootstrap DateTimePicker JS Library. If you would like to replace our implementation with the one you linked that would be excellent!

**Comment by mdavis95** [comment] 2015-06-03 19:43
I don't remember what the issue I had was to be honest but here is the branch I was working on:
https://github.com/mdavis95/gwtbootstrap3-extras/tree/eonasdan

**Comment by Unimax** [comment] 2015-06-03 23:44
@jgodi i know the JS Library difference but needed info on issue faced while writing the wrapper may be because of the moment.js requirement or new events or options . There shouldn't be any issue change (replace) the datetimepicker's JS and writing the wrapper function similar to what currently exits. A heads up would be helpful.

**Comment by Unimax** [comment] 2015-06-07 01:21
@jgodi please check out https://github.com/Unimax/gwtbootstrap3-extras which have a working GWT wrapper i wrote. changed the required resources as well . Will be expecting some refactoring by you and merging into main/master build .
![work](https://cloud.githubusercontent.com/assets/4117562/8022225/9f297b5a-0ce1-11e5-90e1-e3316db2c1aa.png)

**Comment by mdavis95** [comment] 2015-06-07 03:24
I merged master into my fork.
https://github.com/mdavis95/gwtbootstrap3-extras

**Comment by Unimax** [comment] 2015-09-23 01:11
This is the stable gwtwrapper of datetimepicker from http://eonasdan.github.io/bootstrap-datetimepicker/ i am using in my product . Due to less time and little trouble syncing data to my github repo sharing the link of the zip:
https://drive.google.com/open?id=0B6muGxiVGecSdFJFSVhwNlpDYnM
Note not all feature works but all required feature works. I was hoping it could be part of the mail product as its much better then the current version available.

**Comment by crevete** [comment] 2015-12-04 22:29
I cannot reproduce this issue anymore after upgrading library to 2.3.5

**Closed by crevete** 2015-12-04 22:29 UTC
Labels: bug, bug in js library
