### ISSUE TITLE
DateTimePicker day/month/year/decade navigator shows odd behaviour

### ISSUE THREAD

**Issue by mainFC** [gwtbootstrap3/gwtbootstrap3-extras#137] opened 2015-02-23 06:31 UTC
Version 0.8.1 built the navigator arrows as icon tags, "i class="glyphicon glyphicon-arrow-left"".  However, v0.9 builds them as span tags, "span class="glyphicon glyphicon-arrow-left"".  When they use a span the navigation does not work.  It does something odd with the "switch" functionality instead.  You can use the navigation correctly if you are VERY CAREFUL and click the TH entry surrounding the span, "th class="prev" style="visibility: visible;"".  I think v1.0 is also using span and shows similar odd functionality.

**Comment by sb302** [comment] 2015-02-24 16:07
I ran into this issue after upgrading from 0.8.1 to 0.9. Per https://github.com/smalot/bootstrap-datetimepicker/issues/313, the issue is with the minified version bootstrap-datetimepicker.min.js. I took bootstrap-datetimepicker.js, minified it and overwrote bootstrap-datetimepicker-2.3.1.min.cache.js in my project. That appears to have fixed the bug for me.

However, I ran into another bug - https://github.com/smalot/bootstrap-datetimepicker/issues/330, which affects IE8. As per the comments, I replaced indexOf with jQuery.inArray() and it seems to work as expected. 

Both bugs affect the original js library, but I wonder if we should go ahead and patch the version we're using rather than wait for them to release the fix?

**Comment by jgodi** [comment] 2015-03-06 13:44
This is a bug in the underlying library that the DateTimePicker uses: smalot/bootstrap-datetimepicker#313. When that is fixed and a new release, then we will update it.

I'd rather not patch the JS file because on upgrading we will then need to make sure to save all our patches if those fixes aren't in, etc. Just gets extremely messy.

Closing this as #140 will take care of it.

**Closed by jgodi** 2015-03-06 13:44 UTC
